general {
    lock_cmd = pidof hyprlock || hyprlock       # Comando para bloquear
    before_sleep_cmd = loginctl lock-session    # Bloquear antes de suspender
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'  # Encender pantalla al despertar
}

# 1. Si la pantalla ya está bloqueada (hyprlock activo) y pasan 3 minutos (180s) inactiva, apagar monitor
listener {
    timeout = 180
    on-timeout = pidof hyprlock && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# 2. Bloquear la pantalla automáticamente a los 10 minutos (600s) de inactividad
listener {
    timeout = 600
    on-timeout = loginctl lock-session           # Bloquea la pantalla
}

# 3. Apagar la pantalla a los 13 minutos (780s) de inactividad total (por si acaso no se bloqueó manualmente)
listener {
    timeout = 780
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'       # Apaga el monitor
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'         # Lo vuelve a encender al haber actividad
}
