ui {
    # Tamaño grande estilo Ubuntu (ajustado para tu monitor de 3440)
    window_size = 1400 900
}

general {
    grab_focus = true
}

finders {
    # Buscador de aplicaciones por defecto
    default_finder = desktop
    
    # Activar iconos
    desktop_icons = true
}
