# Tokyo Night (Storm) para Hyprland Toolkit
# Aseguramos visibilidad con contrastes claros

background = 0xFF1A1B26
base = 0xFF24283B
alternate_base = 0xFF414868
text = 0xFFC0CAF5
bright_text = 0xFF7AA2F7
accent = 0xFFBB9AF7
accent_secondary = 0xFF7DCFFF
selection = 0xFF33467C
border = 0xFFBB9AF7

icon_theme = breeze-dark
