outputs = "All"
layer = "Overlay"
[modules]
left = ["appLauncher","Updates","Workspaces" ]
center = [ "WindowTitle","MediaPlayer"]
right = [ "SystemInfo",[ "Tempo", "Privacy", "Settings" ] ,["Tray","KeyboardLayout"]]

[media_player]
max_text_length = 50
indicator_format = "Icon"

[[CustomModule]]
name = "appLauncher"
icon = "\uf303"
command = "hyprlauncher"

[settings]
lock_cmd = "hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"
remove_airplane_btn = true
remove_idle_btn = true
indicators = [ "Bluetooth", "Network", "Audio", "Microphone"]

[updates]
check_cmd = "checkupdates; yay -Qum"
update_cmd = 'kitty --title "Actualización del Sistema" -e zsh -c "yay; echo -e \"\nActualización finalizada. Presione Enter para salir...\"; read" &'
interval = 3600

[appearance]
success_color = "#9ece6a"
text_color = "#a9b1d6"
workspace_colors = []

[appearance.primary_color]
base = "#7aa2f7"
weak = "#3b4261"
text = "#1a1b26"

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24283b"
strong = "#7aa2f7"
